version: 2.1
orbs:
  ruby: circleci/ruby@0.1.2 
executors:
  default:
    docker:
      - image: circleci/ruby:2.6.3-stretch-node
jobs:
  build:
    executor: default
    steps:
      - checkout
      - run:
          name: install bundler
          command: gem install bundler:2.1.0
      - run:
          name: Which bundler?
          command: bundle -v
      - ruby/bundle-install
