default: &default
  adapter: mysql2
  encoding: utf8
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
  username: <%= ENV.fetch("SQL_USER") %>
  password: <%= ENV.fetch("SQL_KEY") %>
  socket: /tmp/mysql.sock

development:
  <<: *default
  database: tranker_development

test:
  <<: *default
  database: tranker_test

production:
  <<: *default
  database: tranker_production
  username: tranker
  password: <%= ENV['TRANKER_DATABASE_PASSWORD'] %>
