twitter:
  consumer_key: <%= Rails.application.credentials.dig(:twitter, :consumer_key) %>
  consumer_secret: <%= Rails.application.credentials.dig(:twitter, :consumer_secret) %>
  access_token: <%= Rails.application.credentials.dig(:twitter, :access_token) %>
  access_token_secret: <%= Rails.application.credentials.dig(:twitter, :access_token_secret) %>

get_user_param:
  num: 70
  word: '駆け出しエンジニア'

aggregate_param:
  get_follow_user_num: 3000

truncate_param:
  lookup_max_num: 100
  truncate_criteria: 1000
