twitter:
  consumer_key: <%= Rails.application.credentials.dig(:twitter, :consumer_key) %>
  consumer_secret: <%= Rails.application.credentials.dig(:twitter, :consumer_secret) %>
  access_token: <%= Rails.application.credentials.dig(:twitter, :access_token) %>
  access_token_secret: <%= Rails.application.credentials.dig(:twitter, :access_token_secret) %>
